#Python based docker image
FROM python:3.11.9

RUN apt-get update && apt-get upgrade -y

#Installing Requirements
RUN apt-get install --fix-missing -y curl ffmpeg libavformat-dev libavdevice-dev python3-pip opus-tools

#Updating pip
RUN python3 -m pip install -U pip

COPY . .

RUN python3 -m pip install -U -r requirements.txt
RUN python3 -m pip install -U yt-dlp==2024.7.16

CMD ["python3", "main.py"]
